DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS beers;

CREATE TABLE user (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE beers (
  CHECKIN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CHECKIN_DATE TEXT NOT NULL,
  USER_ID INTEGER NOT NULL,
  BEER_NAME TEXT UNIQUE NOT NULL,
  BREWERY_NAME TEXT NOT NULL,
  BEER_RATING REAL NOT NULL,
  BEER_TYPE TEXT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES user (ID)
);