DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS beers;

CREATE TABLE user (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL,
  REGISTRATION_DATE TIMESTAMP NOT NULL DEFAULT (datetime('now','localtime')),
  USER_IP TEXT NOT NULL
);

CREATE TABLE beers (
  CHECKIN_ID TEXT UNIQUE PRIMARY KEY,
  CHECKIN_DATE TIMESTAMP NOT NULL DEFAULT (datetime('now','localtime')),
  USERNAME TEXT NOT NULL,
  BEER_NAME TEXT NOT NULL,
  BREWERY_NAME TEXT NOT NULL,
  BEER_RATING REAL NOT NULL,
  BEER_TYPE TEXT NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES user (USERNAME)
);