DROP TABLE IF EXISTS beers;

CREATE TABLE beers (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CHECKIN_DATE TEXT NOT NULL,
  BEER_NAME TEXT UNIQUE NOT NULL,
  BREWERY_NAME TEXT NOT NULL,
  BEER_RATING REAL NOT NULL,
  BEER_TYPE TEXT NOT NULL
);